runtime: go
api_version: go1.8

handlers:
- url: /task.*
  script: _go_app
  login: admin
  secure: always
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
- url: /.*
  script: _go_app
  secure: always

nobuild_files:
- vendor

skip_files:
- vendor/.*$
